apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloud-di-zai-dev
# 引用基础配置
resources:
  - ../../base
configMapGenerator:
  - name: configmap
    literals:
      - nacos.host=192.168.1.249
   #files:
      #- configs/production-settings.yml
      #- configs/logback-production.xml
secretGenerator:
  - name: secret
    envs:
      - secrets/.env.dev
