# nginx-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
    #namespace: cloud-di-zai-dev
spec:
  # replicas: 3 # 根据需要调整副本数量
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/rancher/mirrored-library-nginx:1.24.0-alpine
        imagePullPolicy: IfNotPresent   # 或者 Never
           # 添加以下 resources 配置
        resources:
          requests:    # 容器启动所需的最低资源量，调度依据
            cpu: "100m"    # 0.1 个 CPU 核心
            memory: "128Mi" # 128 Mebibytes
          limits:      # 容器允许使用的最大资源量，防止爆炸
            cpu: "200m"    # 最多 0.2 个核心
            memory: "256Mi" # 最多 256 Mebibytes
        ports:
        - name: http-port
          containerPort: 8089
        volumeMounts:
        - name: nginx-shared-storage
          mountPath: /usr/share/nginx/html  # 挂载到默认网页目录
          # readOnly: true  # 如果只需只读，设为true
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-shared-storage
        persistentVolumeClaim:
          claimName: nginx-shared-pvc  # 引用PVC
      - name: nginx-config
        configMap:
          name: nginx-config-a
---
# nginx-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
    #namespace: cloud-di-zai-dev
spec:
  selector:
    app: nginx
  ports:
  - port: 8089
    targetPort: http-port
  # type: NodePort  # 或 LoadBalancer/NodePort 根据需求