apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloud-di-zai-dev

# 引用基础配置
resources:
  - ../../../base/dev
  - ../../../services/nginx
  - host-path-pv.yaml
  - nginx-pvc.yaml
patches:
  - path: deployment-patch.yaml
