ALTER TABLE sys_org 
MODIFY COLUMN id bigint;

ALTER TABLE sys_org 
MODIFY COLUMN PARENT_ID bigint;

ALTER TABLE sys_org 
MODIFY COLUMN DIRECTOR_ID bigint;

ALTER TABLE sys_org 
MODIFY COLUMN CREATE_USER bigint;

ALTER TABLE sys_org 
MODIFY COLUMN UPDATE_USER bigint;