ALTER TABLE sys_relation
ADD COLUMN DELETE_FLAG varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '删除标志';

ALTER TABLE sys_relation
ADD COLUMN CREATE_TIME datetime NULL DEFAULT NULL COMMENT '创建时间';

ALTER TABLE sys_relation
ADD COLUMN CREATE_USER bigint NULL COMMENT '创建用户';

ALTER TABLE sys_relation
ADD COLUMN UPDATE_TIME datetime NULL DEFAULT NULL COMMENT '修改时间';

ALTER TABLE sys_relation
ADD COLUMN UPDATE_USER bigint NULL COMMENT '修改用户';