apiVersion: v1
kind: ConfigMap
metadata:
  name: account-configmap
data:
  db.host: "192.168.1.249"
  db.port: "13306"
  db.name: "auth_center"
  db.user: "auth_center"
  auth.center.host: "auth-center"
