server:
 port: 20000
spring:
  security:
    oauth2:
      client:
        registration:
          certification-catalog-oidc:
            provider: spring
            client-id: certification-catalog
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:20000/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: Certification Catalog
        provider:
          spring:
            issuer-uri: http://auth-server:20001