apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloud-di-zai-dev
# 引用基础配置
resources:
  - ../../../base/dev
  - ../../../services/gateway
# 覆盖镜像名称和标签
images:
- name: docker.io/library/cloud-di-zai-gateway
  newName: docker.io/library/cloud-di-zai-gateway
  newTag: "latest"
patches:
  - path: deployment-patch.yaml
