apiVersion: apps/v1
kind: Deployment
metadata:
  name: role-manage
  labels:
    name: role-manage
spec:
  # replicas: 2
  selector:
    matchLabels:
      name: role-manage
  template:
    metadata:
      labels:
        name: role-manage
    spec:
      containers:
        - name: role-manage
          image: docker.io/library/cloud-di-zai-role-manage:1.0
          imagePullPolicy: IfNotPresent   # 或者 Never
           # 添加以下 resources 配置
          resources:
            requests:    # 容器启动所需的最低资源量，调度依据
              cpu: "100m"    # 0.1 个 CPU 核心
              memory: "300Mi" # 128 Mebibytes
            limits:      # 容器允许使用的最大资源量，防止爆炸
              cpu: "200m"    # 最多 0.2 个核心
              memory: "800Mi" # 最多 256 Mebibytes
          env:
          - name: NACOS_HOST
            valueFrom: 
              configMapKeyRef:
                name: common-configmap         # ConfigMap 名称
                key: nacos.host            # ConfigMap 中的键名
                optional: false          # 如果 ConfigMap 不存在则 Pod 启动失败
          - name: NACOS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: common-secret #secret
                key: nacos.password #secret key
          - name: AUTH_CENTER_HOST
            valueFrom:
              configMapKeyRef:
                name: role-manage-configmap    # ConfigMap 名称
                key: auth.center.host            # ConfigMap 中的键名
                optional: false          # 如果 ConfigMap 不存在则 Pod 启动失败
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: role-manage-configmap    # ConfigMap 名称
                key: db.host            # ConfigMap 中的键名
                optional: false          # 如果 ConfigMap 不存在则 Pod 启动失败
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: role-manage-configmap    # ConfigMap 名称
                key: db.port            # ConfigMap 中的键名
                optional: false          # 如果 ConfigMap 不存在则 Pod 启动失败
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: role-manage-configmap    # ConfigMap 名称
                key: db.name            # ConfigMap 中的键名
                optional: false          # 如果 ConfigMap 不存在则 Pod 启动失败
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: role-manage-configmap    # ConfigMap 名称
                key: db.user            # ConfigMap 中的键名
                optional: false          # 如果 ConfigMap 不存在则 Pod 启动失败
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: role-manage-secret #secret
                key: db.password #secret key
          ports:
          - name: http-port   # 这里给容器端口命名
            containerPort: 20007
---
#service
apiVersion: v1
kind: Service
metadata:
  name: role-manage
spec:
  #type: NodePort #默认是ClusterIP
  ports:
  - port: 20007
    targetPort: http-port
  selector:
    name: role-manage
